// AUTO-GENERATED by apps/shell/scripts/geometry/emit_constants.py — DO NOT EDIT.
// Source of truth: apps/shell/scripts/geometry/*.py
// Logical CSS pixels. Physical/DPI scaling is applied at runtime in the Rust shell.

export const ISLAND_GEOMETRY = {
  idle: { minWidth: 124, height: 44, radius: 22 },
  expanded: { maxWidth: 360, radius: 28 },
  padding: { x: 18, y: 10 },
  shadowPadding: 12,
  anchor: { position: "top-center" as const, topMargin: 12 },
  waveform: {
    compact: { width: 64, height: 24 },
    expanded: { width: 324, height: 80 },
  },
} as const;

export type IslandGeometry = typeof ISLAND_GEOMETRY;
