"""Emit the generated geometry constants consumed by the shell.

Renders:
  - ``apps/shell/src/components/dynamic-island/geometry.generated.ts`` (TS object)
  - ``apps/shell/src-tauri/src/overlay_geometry.rs`` (Rust constants for window sizing)

Usage:
    python apps/shell/scripts/geometry/emit_constants.py
"""

from __future__ import annotations

import pathlib

from pill_geometry import PillGeometry, compute_pill_geometry
from waveform_layout import WaveformLayout, compute_waveform_layout

_BANNER = "// AUTO-GENERATED by apps/shell/scripts/geometry/emit_constants.py — DO NOT EDIT."

# Repo root = three levels up from this file (geometry/ -> scripts/ -> shell/ -> apps/ ... ).
_THIS = pathlib.Path(__file__).resolve()
_REPO_ROOT = _THIS.parents[4]
_TS_OUT = _REPO_ROOT / "apps" / "shell" / "src" / "components" / "dynamic-island" / "geometry.generated.ts"
_RS_OUT = _REPO_ROOT / "apps" / "shell" / "src-tauri" / "src" / "overlay_geometry.rs"


def render_ts(geo: PillGeometry, wf: WaveformLayout) -> str:
    return f"""{_BANNER}
// Source of truth: apps/shell/scripts/geometry/*.py
// Logical CSS pixels. Physical/DPI scaling is applied at runtime in the Rust shell.

export const ISLAND_GEOMETRY = {{
  idle: {{ minWidth: {geo.idle_width}, height: {geo.idle_height}, radius: {geo.radius_idle} }},
  expanded: {{ maxWidth: {geo.expanded_max_width}, radius: {geo.radius_expanded} }},
  padding: {{ x: {geo.padding_x}, y: {geo.padding_y} }},
  shadowPadding: {geo.shadow_padding},
  anchor: {{ position: "top-center" as const, topMargin: {geo.top_margin} }},
  waveform: {{
    compact: {{ width: {wf.compact.width}, height: {wf.compact.height} }},
    expanded: {{ width: {wf.expanded.width}, height: {wf.expanded.height} }},
  }},
}} as const;

export type IslandGeometry = typeof ISLAND_GEOMETRY;
"""


def render_rust(geo: PillGeometry) -> str:
    return f"""{_BANNER}
// Source of truth: apps/shell/scripts/geometry/*.py
// Logical pixels; multiply by the monitor scale factor before sizing the window.

/// Gap below the top edge of the monitor (the notch inset), logical px.
pub const OVERLAY_TOP_MARGIN: i32 = {geo.top_margin};
/// Transparent breathing room reserved around the pill for its drop shadow.
pub const OVERLAY_SHADOW_PADDING: u32 = {geo.shadow_padding};
/// Horizontal anchor of the overlay window. "top-center" centres on the monitor.
pub const OVERLAY_ANCHOR: &str = "{geo.anchor}";
"""


def main() -> None:
    geo = compute_pill_geometry()
    wf = compute_waveform_layout(geo)
    _TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    _RS_OUT.parent.mkdir(parents=True, exist_ok=True)
    _TS_OUT.write_text(render_ts(geo, wf), encoding="utf-8")
    _RS_OUT.write_text(render_rust(geo), encoding="utf-8")
    print(f"wrote {_TS_OUT}")
    print(f"wrote {_RS_OUT}")


if __name__ == "__main__":
    main()
